version: "3.8"

services:
  teamspeak:
    image: teamspeaksystems/teamspeak6-server:latest
    container_name: ultimates-teamspeak6
    restart: unless-stopped
    ports:
      - "9987:9987/udp" # Porta principal de Voz
      - "30033:30033/tcp" # Porta de Transferência de Arquivos
    environment:
      - TSSERVER_LICENSE_ACCEPTED=accept
    volumes:
      - ts-data:/var/tsserver

volumes:
  ts-data:
    name: ultimates-teamspeak6-data
