app = 'ultimate-ts-server'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

# Configuração de portas para o TeamSpeak (UDP para voz e TCP para arquivos/query)
[[services]]
  protocol = 'udp'
  internal_port = 9987

  [[services.ports]]
    port = 9987

[[services]]
  protocol = 'tcp'
  internal_port = 30033

  [[services.ports]]
    port = 30033

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024