app = 'ultimate-ts-server'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

# 1. Mantém a porta UDP 9987 ativa para o tráfego de voz do TeamSpeak
[[services]]
  protocol = 'udp'
  internal_port = 9987
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 9987

# 2. Mantém o serviço HTTP/HTTPS ativo sem desligar a máquina por ociosidade
[http_service]
  internal_port = 30033
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250